
library(tidyverse)
library(magrittr)

df <- data.frame(Host = character(),
                 Virus = character(),
                 HostTaxID = double(),
                 VirusTaxID = double(),
                 HostNCBIResolved = logical(),
                 VirusNCBIResolved = logical(),
                 HostGenus = character(),
                 HostFamily = character(),
                 HostOrder = character(),
                 HostClass = character(),
                 HostSynonyms = character(),
                 VirusGenus = character(),
                 VirusFamily = character(),
                 VirusOrder = character(),
                 VirusClass = character(),
                 HostOriginal = character(),
                 VirusOriginal = character(),
                 HostFlagID = logical(),
                 VirusFlagContaminant = logical(),
                 DetectionMethod = character(),
                 DetectionOriginal = character(),
                 Accession = character(),
                 Database = character(),
                 DatabaseVersion = character(),
                 PublicationYear = double(),
                 CitationID = character(),
                 CitationIDType = character(),
                 ReferenceText = character(),
                 ReleaseYear = double(),
                 ReleaseMonth = double(),
                 ReleaseDay = double(),
                 CollectionYear = double(),
                 CollectionMonth = double(),
                 CollectionDay = double(),
                 stringsAsFactors = FALSE)
                 
write_csv(df, "Intermediate/Template.csv")
